; Envasadora de productos secos — ESP32 + FreeRTOS (Arduino framework)
; Emulación: Wokwi (ver wokwi.toml / diagram.json)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bogde/HX711@^0.7.5
    knolleary/PubSubClient@^2.8
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bblanchon/ArduinoJson@^7.0.0
